lib/renaissance_web/router.ex
defmodule RenaissanceWeb.Router do
  use RenaissanceWeb, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_user
  end

  # Must be called after browser pipeline
  def require_login(conn, _opts) do
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, "You must be logged in to access this page")
      |> redirect(to: "/")
      |> halt()
    end
  end

  def assign_user(conn, _opts) do
    conn
    |> assign(:current_user, get_session(conn, :current_user))
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RenaissanceWeb do
    pipe_through :browser

    get "/", PageController, :index

    pipe_through :require_login

    # TODO: Strip out the count subsystem
    get "/count", CountController, :index
    get "/logout", AuthController, :logout

    resources "/rooms", RoomController
    post "/rooms/:room/send", RoomController, :send
    resources "/characters", CharacterController
    resources "/users", UserController

    resources "/instances",
              InstanceController,
              only: [:index, :new, :create],
              name: "uc",
              param: "id" do
      resources "/", InstanceController, param: "iid"
      get "/:iid/move_to/:roomid", InstanceController, :move_to_room
    end
  end

  scope "/auth", RenaissanceWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", RenaissanceWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: RenaissanceWeb.Telemetry
    end
  end
end

lib/renaissance/embodiment/instance.ex
defmodule Renaissance.Embodiment.Instance do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  schema "embodiment_instances" do
    # TODO: Can we use characterid as the hash key on its own, and just index on userid?
    # HASH KEY compound userid|characterid
    field :id, :string, primary_key: true
    # RANGE KEY
    field :instance_id, :string, default: "default", primary_key: true
    field :userid, :string
    field :characterid, :string
    field :roomid, :string

    timestamps()
  end

  defp compute_id(changeset) do
    case changeset do
      %Ecto.Changeset{changes: %{userid: uid, characterid: cid, id: ucid}} ->
        if ucid == "#{uid}|#{cid}" do
          changeset
        else
          add_error(changeset, :id, "Provided an id that doesn't match the user and character.")
        end

      %Ecto.Changeset{changes: %{userid: uid, characterid: cid}} ->
        put_change(changeset, :id, "#{uid}|#{cid}")

      _ ->
        changeset
    end
  end

  @doc false
  def changeset(instance, attrs) do
    instance
    |> cast(attrs, [:id, :instance_id, :userid, :characterid, :roomid])
    |> compute_id()
    |> validate_required([:id, :userid, :characterid, :roomid])
    # This is actually validating {id, instance_id}, but Ecto and Dynamo don't speak the same language.
    |> unique_constraint(:id)
  end
end

lib/renaissance_web/controllers/instance_controller.ex
defmodule RenaissanceWeb.InstanceController do
  use RenaissanceWeb, :controller

  alias Renaissance.Embodiment
  alias Renaissance.Embodiment.Instance
  alias Renaissance.World

  def index(conn, _params) do
    embodiment_instances = Embodiment.list_embodiment_instances()
    render(conn, "index.html", embodiment_instances: embodiment_instances)
  end

  def new(conn, _params) do
    changeset = Embodiment.change_instance(%Instance{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"instance" => instance_params}) do
    case Embodiment.create_instance(instance_params) do
      {:ok, instance} ->
        conn
        |> put_flash(:info, "Instance created successfully.")
        |> redirect(to: Routes.instance_path(conn, :show, instance))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    instance = Embodiment.get_instance!(id)
    render(conn, "show.html", instance: instance)
  end

  def show(conn, %{"uc_id" => ucid, "iid" => iid}) do
    instance = Embodiment.get_instance!(ucid, iid)

    room = World.get_room_for(instance)
    room_instances = Embodiment.list_instances_for(room)

    characters =
      Enum.map(room_instances, fn %{:characterid => id} -> World.get_character!(id) end)

    messages =
      case Renaissance.Transcript.list_messages_by_channel(room.id) do
        nil -> []
        m -> m
      end

    changeset = Renaissance.Transcript.change_message(%Renaissance.Transcript.Message{})

    render(conn, "show.html",
      instance: instance,
      room: room,
      characters: characters,
      messages: messages,
      changeset: changeset
    )
  end

  def edit(conn, %{"id" => id}) do
    instance = Embodiment.get_instance!(id)
    changeset = Embodiment.change_instance(instance)
    render(conn, "edit.html", instance: instance, changeset: changeset)
  end

  def move_to_room(conn, %{"uc_id" => ucid, "iid" => iid, "roomid" => roomid}) do
    instance = Embodiment.get_instance!(ucid, iid)

    case Embodiment.update_instance(instance, %{roomid: roomid}) do
      {:ok, _} ->
        # This knows WAAAAY too much about the routing. Extract to Routes helper somehow.
        instance_link = "/instances/#{ucid}/#{iid}"

        conn
        |> put_flash(:info, "Instance updated successfully.")
        |> redirect(to: instance_link)

      {:error, _} ->
        instance_link = "/instances/#{ucid}/#{iid}"

        conn
        |> put_flash(:info, "Something bad happened.")
        |> redirect(to: instance_link)
    end
  end

  def update(conn, %{"id" => id, "instance" => instance_params}) do
    instance = Embodiment.get_instance!(id)

    case Embodiment.update_instance(instance, instance_params) do
      {:ok, instance} ->
        conn
        |> put_flash(:info, "Instance updated successfully.")
        |> redirect(to: Routes.instance_path(conn, :show, instance))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", instance: instance, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    instance = Embodiment.get_instance!(id)
    {:ok, _instance} = Embodiment.delete_instance(instance)

    conn
    |> put_flash(:info, "Instance deleted successfully.")
    |> redirect(to: Routes.instance_path(conn, :index))
  end
end

lib/renaissance_web/views/instance_view.ex
defmodule RenaissanceWeb.InstanceView do
  use RenaissanceWeb, :view
end

lib/renaissance_web/templates/instance/edit.html.eex
<h1>Edit Instance</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.instance_path(@conn, :update, @instance)) %>

<span><%= link "Back", to: Routes.instance_path(@conn, :index) %></span>

lib/renaissance_web/templates/instance/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :instance_id %>
  <%= text_input f, :instance_id %>
  <%= error_tag f, :instance_id %>

  <%= label f, :userid %>
  <%= text_input f, :userid %>
  <%= error_tag f, :userid %>

  <%= label f, :characterid %>
  <%= text_input f, :characterid %>
  <%= error_tag f, :characterid %>

  <%= label f, :roomid %>
  <%= text_input f, :roomid %>
  <%= error_tag f, :roomid %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/renaissance_web/templates/instance/index.html.eex
<h1>Listing Embodiment instances</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Characterid</th>
      <th>Roomid</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for instance <- @embodiment_instances do %>
    <tr>
      <td><%= instance.userid %></td>
      <td><%= instance.characterid %></td>
      <td><%= instance.roomid %></td>

      <td>
        <span><%= link "Show", to: "/" %></span>
        <span><%= link "Edit", to: "/" %></span>
        <span><%= link "Delete", to: "/", method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%#
Routes.instance_path(@conn, :show, instance)
Routes.instance_path(@conn, :edit, instance)
Routes.instance_path(@conn, :delete, instance)
%>


<%# <span><%= link "New Instance", to: Routes.instance_path(@conn, :new) % ></span> %>

lib/renaissance_web/templates/instance/new.html.eex
<h1>New Instance</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.instance_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.instance_path(@conn, :index) %></span>

lib/renaissance_web/templates/instance/show.html.eex
<h1>Show Instance</h1>

<div class="description">
  <h1><%= @room.name %></h1>
  <%= for line <- String.split(@room.description, "\u2029") do %>
    <p><%= line %></p>
  <% end %>
</div>

<div class="roster">
  <h2>Characters</h2>
  <ul>
  <%= for character <- @characters do %>
    <% is_me? = (character.id == @instance.characterid) %>
    <li>
      <%= link character.name, to: Routes.character_path(@conn, :show, character) %>
      <%= if is_me? do %>
        (You)
      <% end %>
    </li>
  <% end %>
  </ul>
</div>

<div class="exits">
  <h2>Exits</h2>
  <ul>
  <%# Or with empty map is handling the case where exits is uninitialized in DB.
    This probably isn't necessary forever, but it's useful until we have more thorough validation.
   %>
  <%= for {exit_name, destination} <- @room.exits || %{} do %>
    <% instance = @instance %>
    <%# This knows WAAAAY too much about the routing. Extract to Routes helper somehow. %>
    <% instance_link = "/instances/#{instance.id}/#{instance.instance_id}/move_to/#{destination}" %>
    <li><%= link "Go " <> exit_name, to: instance_link %>
  <% end %>
  </ul>
</div>

<%= render RenaissanceWeb.RoomView, "send.html",
    assigns
    |> Map.put(:send_action, Routes.room_path(@conn, :send, @room))
    |> Map.put(:characters, [%{id: @instance.characterid}])
%>